[package]
name = "genrl_kernels"
version = "0.0.1"
authors = ["Peter Jin <peterhaijin@gmail.com>"]
build = "build.rs"

[lib]
name = "genrl_kernels"
path = "lib.rs"

[build-dependencies]
gcc = "*"

[dependencies]
libc = "*"
